### ISSUE TITLE
Shapefile cacheing stopped working?

### ISSUE THREAD

**Issue by hholzgra** [hholzgra/maposmatic-vagrant#53]
Looks as if right now shapefiles are re-fetched on each provisioning run:

```
    default:      _                       __ _ _
    default:  ___| |__   __ _ _ __   ___ / _(_) | ___  ___
    default: / __| '_ \ / _` | '_ \ / _ \ |_| | |/ _ \/ __|
    default: \__ \ | | | (_| | |_) |  __/  _| | |  __/\__ \
    default: |___/_| |_|\__,_| .__/ \___|_| |_|_|\___||___/
    default:                 |_|
    default: 
    default: Downloading and preprocessing shapefiles
    default: 
    default: downloading land-polygons-split-3857.zip ... unpacking ... indexing
    default: downloading simplified-land-polygons-complete-3857.zip ... unpacking ... indexing
    default: downloading simplified-water-polygons-split-3857.zip ... unpacking ... indexing
    default: downloading water-polygons-split-3857.zip ... unpacking ... indexing
    default: downloading coastlines-split-3857.zip ... unpacking ... indexing
    default: downloading antarctica-icesheet-outlines-3857.zip ... unpacking ... indexing
    default: downloading antarctica-icesheet-polygons-3857.zip ... unpacking ... indexing
    default: downloading lakes-polygons-reduced-3857.zip ... unpacking ... indexing
    default: downloading ocean-polygons-reduced-3857.zip ... unpacking ... indexing
    default: downloading river-polygons-reduced-3857.zip ... unpacking ... indexing
    default: downloading simplified-water-polygons-complete-3857.zip ... unpacking ... indexing
    default: downloading water-polygons-generalized-3857.zip ... unpacking ... indexing
    default: downloading ne_10m_admin_0_boundary_lines_land.zip ... unpacking ... indexing
    default: downloading ne_10m_admin_0_boundary_lines_map_units.zip ... unpacking ... indexing
    default: downloading ne_10m_admin_0_countries_lakes.zip ... unpacking ... indexing
    default: downloading ne_10m_admin_1_states_provinces_lines.zip ... unpacking ... indexing
    default: downloading ne_10m_airports.zip ... unpacking ... indexing
    default: downloading ne_10m_populated_places.zip ... unpacking ... indexing
    default: downloading ne_10m_populated_places_simple.zip ... unpacking ... indexing
    default: downloading ne_10m_roads.zip ... unpacking ... indexing
    default: downloading ne_10m_coastline.zip ... unpacking ... indexing
    default: downloading ne_10m_geography_marine_polys.zip ... unpacking ... indexing
    default: downloading ne_10m_lakes.zip ... unpacking ... indexing
    default: downloading ne_10m_land.zip ... unpacking ... indexing
    default: downloading ne_10m_ocean.zip ... unpacking ... indexing
    default: downloading ne_50m_admin_0_boundary_lines_land.zip ... unpacking ... indexing
    default: downloading ne_50m_admin_0_countries_lakes.zip ... unpacking ... indexing
    default: downloading ne_50m_admin_1_states_provinces_lines.zip ... unpacking ... indexing
    default: downloading ne_50m_geography_marine_polys.zip ... unpacking ... indexing
    default: downloading ne_50m_lakes.zip ... unpacking ... indexing
    default: downloading ne_50m_land.zip ... unpacking ... indexing
    default: downloading ne_110m_admin_0_boundary_lines_land.zip ... unpacking ... indexing
    default: downloading ne_110m_geography_marine_polys.zip ... unpacking ... indexing
    default: downloading gmted25.tar.xz ... unpacking ... indexing
    default: downloading world_boundaries-spherical.tgz ... unpacking ... indexing
    default: downloading shoreline_300.tar.bz2 ... unpacking ... indexing
    default: downloading processed_p.tar.bz2 ... unpacking ... indexing
    default: downloading mercator_tiffs.tar.bz2 ... unpacking ... indexing
    default: 
```
